version: '3'
services:
  hbnet_web_service:
    container_name: hbnet_web_service
    hostname: web_service
    image: kf7eel/hbnet_web_service:latest
    build: 
        dockerfile: ./Dockerfile
        context: ./web
    ports:
      # Port outside container:Port inside container
      - 8084:80
      - 8083:443
    volumes:
       # Path to config.py
       - ./hbnet/web_service/config.py:/opt/hbnet_web/config.py
       # Persist SQLIte data
       - ./hbnet/web_service/data:/opt/hbnet_web/data:rw
       # NGINX logs
       - ./hbnet/log/web_service:/var/log/nginx:rw
       # Path to custon logo
#       - /path/to/logo.png:/opt/hbnet_web/static/HBnet.png
    networks:
      - hbnet_internal

  hbnet_data_gateway:
    container_name: hbnet_data_gateway
    image: kf7eel/hbnet_data_gateway:latest
    hostname: data_gateway
    build:
        dockerfile: ./Dockerfile.data_gateway
        context: .
    volumes:
      - ./hbnet/data_gateway/data_gateway.cfg:/opt/hbnet_data_gateway/config/data_gateway.cfg
       # Persistent data
#       - ./hb_data/data/data_gateway:/opt/hbnet_data_gateway/data:rw
##       # Log file
##       - ./hbnet/log/data_gateway:/opt/hbnet_data_gateway/log:rw
    depends_on:
      - "hbnet_web_service"
    networks:
      - hbnet_internal
    restart: always

  hbnet:
    container_name: hbnet
    image: kf7eel/hbnet:latest
    hostname: hbnet
    build:
        dockerfile: ./Dockerfile.hbnet
        context: .
    ports:
      # Port outside container:Port inside container
      # Port for clients
      - 62032:62032/udp
      - 62033:62033/udp
      # Reporting port for hbmon
      - 4321:4321
    volumes:
      # HBNet Configuration file location
      - ./hbnet/hbnet/hbnet.cfg:/opt/hbnet/config/hbnet.cfg
      # HBNet rules location
      - ./hbnet/hbnet/rules.py:/opt/hbnet/config/rules.py
       # Persistent data
#       - ./hb_data/data/hbnet:/opt/hbnet/data:rw
 ##      # Log file
 ##      - ./hbnet/log/hbnet:/opt/hbnet/log:rw
    depends_on:
      - "hbnet_web_service"
    networks:
      - hbnet_internal
    restart: always




networks:
    hbnet_internal:
        name: hbnet_internal
        driver: bridge   
